/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6a0c31bae4245360f2ce0da02111a628)
interface __BaseEnv_Env {
	VibecoderStore: KVNamespace;
	TEMPLATES_BUCKET: R2Bucket;
	DB: D1Database;
	DISPATCHER: DispatchNamespace;
	API_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	BROWSER: Fetcher;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	TEMPLATES_REPOSITORY: "https://github.com/QuicksilverSlick/vibesdk-templates";
	ALLOWED_EMAIL: "";
	DISPATCH_NAMESPACE: "vibesdk-default-namespace";
	ENABLE_READ_REPLICAS: "true";
	CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
	PLATFORM_CAPABILITIES: {"features":{"app":{"enabled":true},"presentation":{"enabled":false},"general":{"enabled":false}},"version":"1.0.0"};
	CUSTOM_DOMAIN: "app.getdreamforge.com";
	CUSTOM_PREVIEW_DOMAIN: "app.getdreamforge.com";
	MAX_SANDBOX_INSTANCES: "10";
	SANDBOX_INSTANCE_TYPE: "standard-3";
	USE_CLOUDFLARE_IMAGES: false;
	CLOUDFLARE_AI_GATEWAY_TOKEN: string;
	CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
	Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
	DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
	CodebaseAnalyzerObject: DurableObjectNamespace<import("./worker/index").CodebaseAnalyzer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "CodebaseAnalyzer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "PLATFORM_CAPABILITIES" | "CUSTOM_DOMAIN" | "CUSTOM_PREVIEW_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "USE_CLOUDFLARE_IMAGES" | "CLOUDFLARE_AI_GATEWAY_TOKEN">> {}
}
