/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 99e77ac369f9f1f585ac3dc042ea2bcd)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "CodebaseAnalyzer";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		CUSTOM_DOMAIN: "app.getdreamforge.com";
		CUSTOM_PREVIEW_DOMAIN: "app.getdreamforge.com";
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		USE_CLOUDFLARE_IMAGES: false;
		ENVIRONMENT: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		JWT_SECRET: string;
		WEBHOOK_SECRET: string;
		SECRETS_ENCRYPTION_KEY: string;
		ALLOCATION_STRATEGY: string;
		USE_TUNNEL_FOR_PREVIEW: string;
		AI_PROXY_JWT_SECRET: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		CodebaseAnalyzerObject: DurableObjectNamespace<import("./worker/index").CodebaseAnalyzer>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "CLOUDFLARE_AI_GATEWAY" | "CUSTOM_DOMAIN" | "CUSTOM_PREVIEW_DOMAIN" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "USE_CLOUDFLARE_IMAGES" | "ENVIRONMENT" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "GOOGLE_AI_STUDIO_API_KEY" | "JWT_SECRET" | "WEBHOOK_SECRET" | "SECRETS_ENCRYPTION_KEY" | "ALLOCATION_STRATEGY" | "USE_TUNNEL_FOR_PREVIEW" | "AI_PROXY_JWT_SECRET">> {}
}
