/* eslint-disable */
/**
 * Type augmentation for environment bindings that are NOT declared in
 * `wrangler.jsonc`.
 *
 * `worker-configuration.d.ts` is regenerated by `wrangler types`
 * (`bun run cf-typegen`) and only contains bindings declared in
 * `wrangler.jsonc` — vars, KV/R2/D1/DO bindings, etc. Secrets that the
 * worker sets via `wrangler secret put` or via the CF dashboard
 * **never appear there**, because secrets are not part of the wrangler
 * config file.
 *
 * This file declares the additional fields that the worker runtime expects
 * to exist via secrets. TypeScript merges these declarations with the
 * generated ones so `env.ANTHROPIC_API_KEY` etc. are typed correctly
 * without `(env as any)` casts.
 *
 * We declare the same shape on both `Cloudflare.Env` and the global `Env`
 * interface. wrangler types ≥4.91 emit
 * `interface Env extends __BaseEnv_Env {}` rather than
 * `interface Env extends Cloudflare.Env {}`, so augmentations that only
 * extend `Cloudflare.Env` no longer reach the global `Env` symbol that
 * `env` parameters and `cloudflare:workers`' exported `env` are typed
 * against. Declaration-merging on both keeps the typing complete across
 * the wrangler version range.
 *
 * Maintaining this file:
 *  - When you add a new secret via `wrangler secret put FOO`, add a
 *    matching entry here (typed as `string` unless you know better).
 *  - When you remove a secret, remove it here too — TypeScript won't
 *    catch references to a now-missing binding without this file's help.
 *  - When you add a regular `var` to `wrangler.jsonc`, do **not** add it
 *    here — let `wrangler types` pick it up in `worker-configuration.d.ts`.
 *
 * The list below mirrors the secrets visible on the production worker
 * (`wrangler versions view <id> --name dreamforge-cf` shows them under
 * "Secret Name:"). Keep them in sync.
 */
declare namespace Cloudflare {
    interface Env {
        // AI model provider keys
        ANTHROPIC_API_KEY: string;
        OPENAI_API_KEY: string;
        GOOGLE_AI_STUDIO_API_KEY: string;
        OPENROUTER_API_KEY: string;
        CEREBRAS_API_KEY: string;
        GROQ_API_KEY: string;
        SERPAPI_KEY: string;

        // Cloudflare API access (used by the deploy script and image upload)
        CLOUDFLARE_API_TOKEN: string;
        CLOUDFLARE_ACCOUNT_ID: string;
        CLOUDFLARE_AI_GATEWAY_URL: string;
        CLOUDFLARE_AI_GATEWAY_TOKEN: string;
        CF_ACCOUNT_ID: string;
        CF_AI_GATEWAY_ID: string;

        // Sandbox / runner service
        SANDBOX_SERVICE_API_KEY: string;
        SANDBOX_SERVICE_TYPE: string;
        SANDBOX_SERVICE_URL: string;

        // OAuth providers
        GOOGLE_CLIENT_ID: string;
        GOOGLE_CLIENT_SECRET: string;
        GITHUB_CLIENT_ID: string;
        GITHUB_CLIENT_SECRET: string;
        GITHUB_EXPORTER_CLIENT_ID: string;
        GITHUB_EXPORTER_CLIENT_SECRET: string;

        // Cloudflare OAuth Connect (used by PR 10a CF account/gateway linking).
        // When ENABLE_CLOUDFLARE_LIMITS !== 'true' the feature is disabled and
        // these values are unused at runtime; they're typed as optional so the
        // worker can boot without them in self-hosted deployments.
        ENABLE_CLOUDFLARE_LIMITS?: string;
        CLOUDFLARE_OAUTH_CLIENT_ID?: string;
        CLOUDFLARE_OAUTH_CLIENT_SECRET?: string;
        CLOUDFLARE_OAUTH_AUTH_URL?: string;
        CLOUDFLARE_OAUTH_TOKEN_URL?: string;
        CLOUDFLARE_OAUTH_USERINFO_URL?: string;
        CLOUDFLARE_OAUTH_SCOPES?: string;
        CF_OAUTH_ENCRYPTION_KEY?: string;

        // Auth + crypto
        JWT_SECRET: string;
        AI_PROXY_JWT_SECRET: string;
        ENTROPY_KEY: string;
        SECRETS_ENCRYPTION_KEY: string;

        // Cloudflare Access (Zero Trust) — internal service auth
        CF_ACCESS_ID: string;
        CF_ACCESS_SECRET: string;

        // Misc runtime config
        ENVIRONMENT: string;
        ALLOCATION_STRATEGY: string;
        USE_TUNNEL_FOR_PREVIEW: boolean;
        // Comma-separated user ids exempt from usage rate limits. Optional:
        // the worker boots without it (no exemptions).
        RATE_LIMIT_EXEMPT_USER_IDS?: string;

        // Operator admin console kill-switch. When set to 'false' the whole
        // /api/admin/* group 404s without a redeploy (set as a secret/var via
        // the dashboard). Absent or any other value => enabled (default on).
        ADMIN_CONSOLE_ENABLED?: string;

        // Observability
        SENTRY_DSN: string;
    }
}

// Mirror the same augmentation onto the global `Env` interface. The
// wrangler-generated `worker-configuration.d.ts` declares
// `interface Env extends __BaseEnv_Env {}` at the top level (since
// wrangler 4.91), so secrets need to be merged here too — augmenting only
// `Cloudflare.Env` no longer flows through to the `env` parameter types.
interface Env {
    ANTHROPIC_API_KEY: string;
    OPENAI_API_KEY: string;
    GOOGLE_AI_STUDIO_API_KEY: string;
    OPENROUTER_API_KEY: string;
    CEREBRAS_API_KEY: string;
    GROQ_API_KEY: string;
    SERPAPI_KEY: string;

    CLOUDFLARE_API_TOKEN: string;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_AI_GATEWAY_URL: string;
    CLOUDFLARE_AI_GATEWAY_TOKEN: string;
    CF_ACCOUNT_ID: string;
    CF_AI_GATEWAY_ID: string;

    SANDBOX_SERVICE_API_KEY: string;
    SANDBOX_SERVICE_TYPE: string;
    SANDBOX_SERVICE_URL: string;

    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    GITHUB_EXPORTER_CLIENT_ID: string;
    GITHUB_EXPORTER_CLIENT_SECRET: string;

    ENABLE_CLOUDFLARE_LIMITS?: string;
    CLOUDFLARE_OAUTH_CLIENT_ID?: string;
    CLOUDFLARE_OAUTH_CLIENT_SECRET?: string;
    CLOUDFLARE_OAUTH_AUTH_URL?: string;
    CLOUDFLARE_OAUTH_TOKEN_URL?: string;
    CLOUDFLARE_OAUTH_USERINFO_URL?: string;
    CLOUDFLARE_OAUTH_SCOPES?: string;
    CF_OAUTH_ENCRYPTION_KEY?: string;

    JWT_SECRET: string;
    AI_PROXY_JWT_SECRET: string;
    ENTROPY_KEY: string;
    SECRETS_ENCRYPTION_KEY: string;

    CF_ACCESS_ID: string;
    CF_ACCESS_SECRET: string;

    ENVIRONMENT: string;
    ALLOCATION_STRATEGY: string;
    USE_TUNNEL_FOR_PREVIEW: boolean;
    RATE_LIMIT_EXEMPT_USER_IDS?: string;
    ADMIN_CONSOLE_ENABLED?: string;

    SENTRY_DSN: string;
}

// NOTE: do NOT add `export {}` here. `declare namespace Cloudflare` and
// the global `interface Env` augmentations merge with the wrangler-
// generated declarations only when this file is treated as a global
// script (no imports/exports). Adding `export` makes it a module and
// breaks the merge — TypeScript will then complain that
// `env.ANTHROPIC_API_KEY` etc. don't exist.
