/**
 * Agent type surface — ported from upstream `cloudflare/vibesdk`
 * `worker/agents/core/types.ts`. Adds the per-behavior init-arg
 * discriminated union (`PhasicAgentInitArgs` / `AgenticAgentInitArgs`),
 * deploy/export result shapes, and `RuntimeType`. Preserves the fork's
 * `AllIssues.clientErrors` field (FastCodeFixer dep).
 */

import type {
    GitHubPushRequest,
    RuntimeError,
    StaticAnalysisResponse,
    TemplateDetails,
} from '../../services/sandbox/sandboxTypes';
import type {
    ClientReportedErrorType,
    FileOutputType,
    PhaseConceptType,
    TemplateSelection,
} from '../schemas';
import type { ConversationMessage } from '../inferutils/common';
import type { InferenceContext } from '../inferutils/config.types';
import type { ProcessedImageAttachment } from '../../types/image-attachment';
import type { InterviewSpec } from '../interview/types';
import type { AgenticState, CurrentDevState, PhasicState } from './state';

/**
 * Generation behavior. Phasic agents iterate phase-by-phase; agentic
 * agents run a single open-ended LLM-orchestrated loop. Determined per
 * project type via the features registry.
 */
export type BehaviorType = 'phasic' | 'agentic';

/**
 * Project category that the agent is generating. Drives feature gating
 * in the platform capabilities registry (`worker/agents/core/features/`).
 */
export type ProjectType = 'app' | 'workflow' | 'presentation' | 'general';

/**
 * Where the project runs during preview/dev.
 *  - `sandbox`: Cloudflare Containers (full apps with UI)
 *  - `worker`:  dynamic Worker Loaders (backend only)
 *  - `none`:    no runtime (static export only)
 */
export type RuntimeType = 'sandbox' | 'worker' | 'none';

// ---------------------------------------------------------------------------
// Initialization arguments
// ---------------------------------------------------------------------------

/** Fields common to every behavior at init time. */
interface BaseAgentInitArgs {
    query: string;
    hostname: string;
    inferenceContext: InferenceContext;
    language?: string;
    frameworks?: string[];
    images?: ProcessedImageAttachment[];
    /** Structured requirements from the intake interview, when one ran. */
    interviewSpec?: InterviewSpec | null;
    onBlueprintChunk: (chunk: string) => void;
    /**
     * Generated by `CodeGeneratorAgent`, threaded into behavior init.
     *
     * Required during the M3 transition so legacy `simpleGeneratorAgent.ts`
     * destructures cleanly. The new agent (commits 2+) populates this on
     * every init call. Upstream keeps it optional; after M3 commit 4
     * deletes the legacy file we can widen back to `?` if upstream's
     * callsites benefit.
     */
    sandboxSessionId: string;
}

/**
 * Phasic init requires a template — the phase generation operation seeds
 * its blueprint from the resolved template structure.
 */
interface PhasicAgentInitArgs extends BaseAgentInitArgs {
    templateInfo: {
        templateDetails: TemplateDetails;
        selection: TemplateSelection;
    };
}

/**
 * Agentic init makes the template optional — BYOP imports do not have one
 * and the agentic blueprint synthesizer resolves the project structure
 * from the analyzed repository instead.
 */
interface AgenticAgentInitArgs extends BaseAgentInitArgs {
    templateInfo?: {
        templateDetails: TemplateDetails;
        selection: TemplateSelection;
    };
}

/**
 * State-type-driven init-args resolution. Lets behavior implementations
 * declare their required init shape in their generic parameter and have
 * the union resolve at the call boundary.
 *
 * **Default parameter is `PhasicState`** — not the `PhasicState | AgenticState`
 * union — so the bare `AgentInitArgs` (no generic) resolves to
 * `PhasicAgentInitArgs` (templateInfo required) for backward compatibility
 * with the legacy `simpleGeneratorAgent.ts` consumer. That file is
 * deleted in M3 commit 4; at commit 5 the default can be widened to
 * the union if upstream's call patterns benefit from it.
 */
export type AgentInitArgs<
    TState extends PhasicState | AgenticState = PhasicState,
> = TState extends PhasicState
    ? PhasicAgentInitArgs
    : TState extends AgenticState
        ? AgenticAgentInitArgs
        : PhasicAgentInitArgs | AgenticAgentInitArgs;

// ---------------------------------------------------------------------------
// Behavior surface
// ---------------------------------------------------------------------------

/**
 * Free-form plan string the agentic behavior maintains as a working
 * document across LLM iterations. Upstream keeps this as plain `string`
 * rather than a structured shape because the agentic prompts expect
 * whatever the model emits as the canonical plan.
 */
export type Plan = string;

/**
 * Aggregated issue feed consumed by the code-review and fast-fix paths.
 *
 * `clientErrors` is fork-only: the typed runtime-error report from
 * preview iframes that FastCodeFixer uses to target regenerations.
 * Preserved here even though upstream's `AllIssues` does not have it.
 */
export interface AllIssues {
    runtimeErrors: RuntimeError[];
    staticAnalysis: StaticAnalysisResponse;
    clientErrors: ClientReportedErrorType[];
}

// ---------------------------------------------------------------------------
// Screenshot + summary surfaces
// ---------------------------------------------------------------------------

export interface ScreenshotData {
    url: string;
    timestamp: number;
    viewport: { width: number; height: number };
    userAgent?: string;
    /** Base64 data URL from Cloudflare Browser Rendering REST API. */
    screenshot?: string;
}

export interface AgentSummary {
    query: string;
    generatedCode: FileOutputType[];
    /** Optional — agents that haven't conversed yet won't have a history. */
    conversation?: ConversationMessage[];
}

export interface UserContext {
    suggestions?: string[];
    images?: ProcessedImageAttachment[];
}

export interface PhaseExecutionResult {
    currentDevState: CurrentDevState;
    staticAnalysis?: StaticAnalysisResponse;
    result?: PhaseConceptType;
    userSuggestions?: string[];
    userContext?: UserContext;
}

// ---------------------------------------------------------------------------
// Deep-debug + deploy/export result shapes
// ---------------------------------------------------------------------------

export type DeepDebugResult =
    | { success: true; transcript: string }
    | { success: false; error: string };

export type DeploymentTarget = 'platform' | 'user';

export interface DeployResult {
    success: boolean;
    target: DeploymentTarget;
    url?: string;
    deploymentId?: string;
    error?: string;
    metadata?: Record<string, unknown>;
}

export interface DeployOptions {
    target?: DeploymentTarget;
    token?: string;
    metadata?: Record<string, unknown>;
}

export interface ExportResult {
    success: boolean;
    url?: string;
    error?: string;
    metadata?: Record<string, unknown>;
}

/**
 * Options for project export / deployment. The `kind` enumerates the
 * supported export targets exposed through the features registry.
 */
export interface ExportOptions {
    kind: 'github' | 'pdf' | 'pptx' | 'googleslides' | 'workflow';
    format?: string;
    token?: string;
    github?: GitHubPushRequest;
    metadata?: Record<string, unknown>;
}
